Pagination UI
scale-it/sigmadao-ui pull request #40
Opened 2022-05-29 14:27 UTC by Megha-Dev-19

![image](https://user-images.githubusercontent.com/100185149/170873619-3aa2f6f2-b0e2-4de3-932a-2031997d6b56.png)

- when no data exists
![image](https://user-images.githubusercontent.com/100185149/170874314-18faa232-76aa-4084-9643-9e43ecbe4d1a.png)

@robert-zaremba let me know if you need any changes to the UI

2022-05-30 15:56 UTC, rmeena840 reviewed
Backedn PR has to be merged first.

2022-05-30 20:04 UTC, robert-zaremba commented
UI looks good.  I didn't check the code though

2022-06-03 14:22 UTC, rmeena840 requested changes
Reviewed. Creating an enum for navigation would save a lot of code lines. I would suggest going with this approach.

2022-06-03 14:22 UTC, rmeena840 commented on src/pages/AllDao.vue
> +						let dataExists: boolean;
I would suggest this.
```suggestion
						let isCached: boolean;
```

2022-06-03 14:25 UTC, rmeena840 requested changes

2022-06-03 14:25 UTC, rmeena840 commented on src/pages/AllDao.vue
> +							dataExists = false;
No need to set `false ` here. initialize line 359 'isCached' with false.

2022-06-07 10:54 UTC, rmeena840 commented on src/pages/AllDao.vue
> +					@click="handlePaginationCall(PaginationCallType.PREVIOUS)"
```suggestion
					@click="handlePaginationCall(PaginationCallType.NAV_PREV)"
```

2022-06-07 10:55 UTC, rmeena840 commented on src/pages/AllDao.vue
> +					@click="handlePaginationCall(PaginationCallType.NEXT)"
```suggestion
					@click="handlePaginationCall(PaginationCallType.NAV_NEXT)"
```

2022-06-07 10:58 UTC, rmeena840 approved these changes
Pre-approving. Look at suggestions.

2022-06-07 10:58 UTC, rmeena840 commented on src/pages/AllDao.vue
> +					this.fetchDataForDAO(
```suggestion
					this.fetchDaoData(
```

2022-06-07 11:05 UTC, Megha-Dev-19 commented on src/pages/AllDao.vue
> +					@click="handlePaginationCall(PaginationCallType.PREVIOUS)"
updated

2022-06-07 11:05 UTC, Megha-Dev-19 commented on src/pages/AllDao.vue
> +					this.fetchDataForDAO(
updated

2022-06-07 11:06 UTC, merged